# Generated by Django 4.0 on 2022-02-18 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import submissions.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Název')),
            ],
            options={
                'verbose_name': 'Klíčové slovo',
                'verbose_name_plural': 'Klíčová slova',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Interní kód')),
                ('name', models.CharField(max_length=32, verbose_name='Název')),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=True, verbose_name='Zadání schváleno?')),
                ('is_submitted', models.BooleanField(default=True, verbose_name='Práce odevzdána?')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Práce uzavřena?')),
                ('is_public', models.BooleanField(default=False, verbose_name='Práce zveřejněná?')),
            ],
            options={
                'verbose_name': 'Stav',
                'verbose_name_plural': 'Stavy',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Název')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='submissions.subject', verbose_name='Rodičovský předmět')),
            ],
            options={
                'verbose_name': 'Předmět',
                'verbose_name_plural': 'Předměty',
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('submissionattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submissions.submissionattachment')),
                ('upload', models.FileField(upload_to=submissions.models.upload_path)),
            ],
            bases=('submissions.submissionattachment',),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('submissionattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submissions.submissionattachment')),
                ('url', models.URLField()),
            ],
            bases=('submissions.submissionattachment',),
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Název')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Abstrakt')),
                ('year', models.IntegerField(default=submissions.models.current_year, verbose_name='Ročník')),
                ('assignment', models.TextField(blank=True, null=True, verbose_name='Zadání')),
                ('supervisor_opinion', models.TextField(blank=True, null=True, verbose_name='Posudek vedoucího')),
                ('opponent_opinion', models.TextField(blank=True, null=True, verbose_name='Posudek oponenta')),
                ('mark', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'výborně'), (2, 'chvalitebně'), (3, 'dobře'), (4, 'dostatečně'), (5, 'nedostatečně')], null=True, verbose_name='Známka')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('keywords', models.ManyToManyField(blank=True, to='submissions.Keyword', verbose_name='Klíčová slova')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opposed', to=settings.AUTH_USER_MODEL, verbose_name='Oponent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theses', to='submissions.subject', verbose_name='Předmět')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised', to=settings.AUTH_USER_MODEL, verbose_name='Vedoucí')),
            ],
            options={
                'verbose_name': 'Práce',
                'verbose_name_plural': 'Práce',
                'permissions': [('author', 'Může být autor'), ('supervisor', 'Může být vedoucí'), ('opponent', 'Může být oponent')],
            },
        ),
        migrations.AddField(
            model_name='submissionattachment',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='submissions.thesis'),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Čas')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', to='submissions.state', verbose_name='Stav')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='submissions.thesis', verbose_name='Práce')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL, verbose_name='Měnil')),
            ],
            options={
                'verbose_name': 'Záznam',
                'verbose_name_plural': 'Záznamy',
            },
        ),
        migrations.CreateModel(
            name='ConsultationPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Počet potřebných konzultací')),
                ('start', models.DateField(verbose_name='Začátek')),
                ('end', models.DateField(verbose_name='Konec')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='submissions.subject', verbose_name='Předmět')),
            ],
            options={
                'verbose_name': 'Období povinných konzultací',
                'verbose_name_plural': 'Období povinných konzultací',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Datum')),
                ('note', models.TextField(blank=True, verbose_name='Poznámky')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='submissions.consultationperiod', verbose_name='Období')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='submissions.thesis', verbose_name='Práce')),
            ],
            options={
                'verbose_name': 'Konzultace',
                'verbose_name_plural': 'Konzultace',
            },
        ),
    ]
